services:
  rachael-eureka:
    build: ./rachael-eureka-server
    ports:
      - "8761:8761"
    networks:
      - rachael-net

  rachael-config:
    build: ./rachael-config-server
    ports:
      - "8888:8888"
    depends_on:
      - rachael-eureka
    networks:
      - rachael-net

  rachael-api-user:
    build: ./rachael-api-user
    ports:
      - "8900:8900"
    depends_on:
      - rachael-eureka
      - rachael-config
    restart: on-failure
    networks:
      - rachael-net

  rachael-api-wallet:
      build: ./rachael-api-wallet
      ports:
        - "8901:8901"
      depends_on:
        - rachael-eureka
        - rachael-config
      restart: on-failure
      networks:
        - rachael-net

  rachael-api-album:
      build: ./rachael-api-album
      ports:
        - "8902:8902"
      depends_on:
        - rachael-eureka
        - rachael-config
      restart: on-failure
      networks:
        - rachael-net

  rachael-frontend:
    build: ./rachael-frontend
    ports:
      - "8080:8080"
    depends_on:
      - rachael-eureka
      - rachael-config
    networks:
      - rachael-net

networks:
  rachael-net:
    driver: bridge

