server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://lucamezzolla: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@github.com/lucamezzolla/rachael-config-repo.git
          clone-on-start: true
          default-label: development

eureka:
  client:
    service-url:
      defaultZone: http://rachael-eureka:8761/eureka					
