server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lucamezzolla/rachael.git
          searchPaths: rachael-config-repo
          default-label: master
          username: lucamezzolla
          password: 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
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: http://rachael-eureka:8761/eureka
