server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:../rachael-config-repo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#ricorda di far partire in locale con il profilo native