spring:
  application:
    name: rachael-api-wallet
  datasource:
    url: jdbc:mariadb://rachael-mariadb:3306/rachael_wallet_db
    username: luca
    password: trustno1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.MariaDBDialect

server:
  port: 8901
  
eureka:
  client:
    service-url:
      defaultZone: http://rachael-eureka:8761/eureka
