spring:
  application:
    name: rachael-api-user
  datasource:
    url: jdbc:mariadb://172.30.0.1:3306/rachael_user_db
    username: rachael
    password: rachael
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

server:
  port: 8900

eureka:
  client:
    service-url:
      defaultZone: http://rachael-eureka:8761/eureka
